### ISSUE TITLE
would it be possible to config the position (left or right) in Settings ?

### ISSUE THREAD

**Issue by niaodan2b** [RambIT-nl/highlight-counter#1]
I came from Atom so I really love your extension, and thanks for your work.
In recent update the alignment was changed from the left to the right, which is not a big deal but, personally I feel it harder to locate the counter at a glance, maybe because the width of the right side information in status bar floats much more than the left side.
So, this might be a trival issue but, would it be possible to have a configuration on this?

**Comment by ramon-nl** [comment]
Good to hear that this extension is useful for you.

Thank you for your feature request. I have released version 1.2.0 with the option to configure the alignment of the highlight counter in the status bar. The alignment changed to the right in version 1.1.0, because relevant information about the cursor position and the amount of selected characters is also aligned to the right.

Please let me know if you have any questions.

**Comment by niaodan2b** [comment]
Thank you so much for the new version !

Just why is it before "Errors & Warnings" now ? I remember it being the rightmost in 1.0 . 

![](https://i.imgur.com/ZtAuXNx.jpg)

What determines the order ?

**Comment by niaodan2b** [comment]
Not a big deal though. I don't care about this, just curious.

**Comment by ramon-nl** [comment]
The extension uses a different way to set a status bar message since version 1.1.0. The function createStatusBarItem allows to set a priority. I have set it to 100, so that has to be the cause of the different order.

**Comment by niaodan2b** [comment]
Thanks for the explaination
